<a href="https://colab.research.google.com/github/hyeonseong0917/NLP_study/blob/main/text_generation_gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Tue May  2 07:52:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!pip install transformers accelerate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


[Code Reference](https://velog.io/@gtpgg1013/kogpt-%ED%95%9C%EA%B5%AD%EC%96%B4-%EC%83%9D%EC%84%B1-GPT-3-%EB%AA%85%EB%AC%B8%EA%B0%80-%EB%82%A9%EC%8B%9C%EC%98%A4)

[Code Reference2](https://littlefoxdiary.tistory.com/46)



In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM 
"""
tokenizer = AutoTokenizer.from_pretrained(
  'kakaobrain/kogpt', revision='KoGPT6B-ryan1.5b-float16',  # or float32 version: revision=KoGPT6B-ryan1.5b
  bos_token='[BOS]', eos_token='[EOS]', unk_token='[UNK]', pad_token='[PAD]', mask_token='[MASK]'
)
model = AutoModelForCausalLM.from_pretrained(
  'kakaobrain/kogpt', revision='KoGPT6B-ryan1.5b-float16',  # or float32 version: revision=KoGPT6B-ryan1.5b
  pad_token_id=tokenizer.eos_token_id,
  torch_dtype='auto', low_cpu_mem_usage=True
).to(device='cuda', non_blocking=True)
_ = model.eval()
"""
import numpy as np
import random
import tensorflow as tf
from transformers import AutoTokenizer
from transformers import TFGPT2LMHeadModel
from transformers import GPTJForCausalLM, AutoTokenizer
model = TFGPT2LMHeadModel.from_pretrained('skt/kogpt2-base-v2', from_pt=True)
tokenizer = AutoTokenizer.from_pretrained('skt/kogpt2-base-v2')
# tokenizer = AutoTokenizer.from_pretrained('MrBananaHuman/kogpt_6b_fp16', bos_token='[BOS]', eos_token='[EOS]', unk_token='[UNK]', pad_token='[PAD]', mask_token='[MASK]')

# model = GPTJForCausalLM.from_pretrained('MrBananaHuman/kogpt_6b_fp16', pad_token_id=tokenizer.eos_token_id, torch_dtype='auto', low_cpu_mem_usage=True)
# model.to('cuda', non_blocking=True)
# _ = model.eval()




Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFGPT2LMHeadModel: ['lm_head.weight', 'transformer.h.6.attn.masked_bias', 'transformer.h.0.attn.masked_bias', 'transformer.h.8.attn.masked_bias', 'transformer.h.4.attn.masked_bias', 'transformer.h.9.attn.masked_bias', 'transformer.h.5.attn.masked_bias', 'transformer.h.1.attn.masked_bias', 'transformer.h.2.attn.masked_bias', 'transformer.h.3.attn.masked_bias', 'transformer.h.11.attn.masked_bias', 'transformer.h.10.attn.masked_bias', 'transformer.h.7.attn.masked_bias']
- This IS expected if you are initializing TFGPT2LMHeadModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFGPT2LMHeadModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassifica

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [ ]:
sent = '근육이 커지기 위해서는'

In [ ]:
input_ids = tokenizer.encode(sent)
input_ids = tf.convert_to_tensor([input_ids])
print(input_ids)
output = model.generate(input_ids,
                        max_length=128,
                        repetition_penalty=2.0,
                        use_cache=True)
output_ids = output.numpy().tolist()[0]
print(output_ids)

tf.Tensor([[33245 10114 12748 11357]], shape=(1, 4), dtype=int32)
[33245, 10114, 12748, 11357, 23879, 39306, 9684, 7884, 10211, 15177, 26421, 387, 17339, 7889, 9908, 15768, 6903, 15386, 8146, 12923, 9228, 18651, 42600, 9564, 17764, 9033, 9199, 14441, 7335, 8704, 12557, 32030, 9510, 18595, 9025, 10571, 25741, 10599, 13229, 9508, 7965, 8425, 33102, 9122, 21240, 9801, 32106, 13579, 12442, 13235, 19430, 8022, 12972, 9566, 11178, 9554, 24873, 7198, 9391, 12486, 8711, 9346, 7071, 36736, 9693, 12006, 9038, 10279, 36122, 9960, 8405, 10826, 18988, 25998, 9292, 7671, 9465, 7489, 9277, 10137, 9677, 9248, 9912, 12834, 11488, 13417, 7407, 8428, 8137, 9430, 14222, 11356, 10061, 9885, 19265, 9377, 20305, 7991, 9178, 9648, 9133, 10021, 10138, 30315, 21833, 9362, 9301, 9685, 11584, 9447, 42129, 10124, 7532, 17932, 47123, 37544, 9355, 15632, 9124, 10536, 13530, 12204, 9184, 36152, 9673, 9788, 9029, 11764]


In [ ]:
tokenizer.decode(output_ids)

'근육이 커지기 위해서는 무엇보다 규칙적인 생활습관이 중요하다.\n특히, 아침식사는 단백질과 비타민이 풍부한 과일과 채소를 많이 섭취하는 것이 좋다.\n또한 하루 30분 이상 충분한 수면을 취하는 것도 도움이 된다.\n아침 식사를 거르지 않고 규칙적으로 운동을 하면 혈액순환에 도움을 줄 뿐만 아니라 신진대사를 촉진해 체내 노폐물을 배출하고 혈압을 낮춰준다.\n운동은 하루에 10분 정도만 하는 게 좋으며 운동 후에는 반드시 스트레칭을 통해 근육량을 늘리고 유연성을 높여야 한다.\n운동 후 바로 잠자리에 드는 것은 피해야 하며 특히 아침에 일어나면 몸이 피곤해지기 때문에 무리하게 움직이면 오히려 역효과가 날 수도 있다.\n운동을'

In [ ]:
output = model(input_ids)
top5 = tf.math.top_k(output.logits[0, -1], k=10000)
print(type(top5))
m=tokenizer.convert_ids_to_tokens(top5.indices.numpy())
m=m[len(m)-6 :len(m)]
print(m)
# print(len(m))
# for i in range(1,5):
#   print(m[len(m)-i])

<class 'tensorflow.python.ops.gen_nn_ops.TopKV2'>
['▁화려', '▁73', '▁방법으로', '▁동전을', '▁들여', '▁자문']


In [ ]:
sent = '근육이 커지기 위해서는'
input_ids = tokenizer.encode(sent)
print(type(input_ids))
print(input_ids)
while len(input_ids) < 50:
    output = model(np.array([input_ids]))
    # Top 5의 단어들을 추출
    top5 = tf.math.top_k(output.logits[0, -1], k=1000)
    # top5=top5[len(top5)-5:len(top5)]
    k=tokenizer.convert_ids_to_tokens(top5.indices.numpy())
    k=k[len(k)-6 :len(k)]
    # k=np.array(k)
    # print(type(top5.indices.numpy()))
    # print(type(k))
    for i in range(len(k)):
      k[i]=tokenizer.encode(k[i])
    # print(k)      
    # print(tokenizer[k]["input_ids"])
    # break
    # Top 5의 단어들 중 랜덤으로 다음 단어로 선택.
    # token_id = random.choice(top5.indices.numpy())
    token_id = random.choice(k)
    # print(token_id)
    # print(type(token_id))
    # print(tokenizer.decode(token_id))
    
    input_ids.append(token_id[0])
    # break

tokenizer.decode(input_ids)

<class 'list'>
[33245, 10114, 12748, 11357]


'근육이 커지기 위해서는 교통 담 백 근 얼마나 충 부 해 망 갑 상 날아 먹이 듯 곤 더 밟 어 무릎 아예 다가 일으 소리 이리 재미 발 선 슈 스키 멧 인가 산을 녹여 청 어 뼈를 들여다 괴. 징 자국 하나가 한번 물을 적에 걸러'

In [ ]:
print(type(top5))
print(top5[len(top5)-5:len(top5)])

<class 'tensorflow.python.ops.gen_nn_ops.TopKV2'>
(<tf.Tensor: shape=(1000,), dtype=float32, numpy=
array([11.5373535, 10.073083 ,  9.944405 ,  9.874777 ,  9.64585  ,
        9.53906  ,  9.523936 ,  9.52004  ,  9.359821 ,  9.210946 ,
        9.206393 ,  9.192377 ,  9.138684 ,  9.103445 ,  9.076993 ,
        9.039064 ,  9.009724 ,  8.927725 ,  8.892429 ,  8.8671465,
        8.842289 ,  8.772652 ,  8.768754 ,  8.737794 ,  8.734391 ,
        8.734124 ,  8.730579 ,  8.721138 ,  8.68109  ,  8.613301 ,
        8.607966 ,  8.595046 ,  8.564957 ,  8.562681 ,  8.555201 ,
        8.533952 ,  8.518273 ,  8.480756 ,  8.46956  ,  8.455201 ,
        8.402275 ,  8.400044 ,  8.334945 ,  8.31808  ,  8.314565 ,
        8.296791 ,  8.2918215,  8.276949 ,  8.275611 ,  8.269139 ,
        8.256231 ,  8.240455 ,  8.22493  ,  8.211713 ,  8.17937  ,
        8.135791 ,  8.130085 ,  8.126602 ,  8.099544 ,  8.09632  ,
        8.096167 ,  8.09265  ,  8.079878 ,  8.069183 ,  8.048207 ,
        8.046988 ,  7.983058 

In [ ]:
prompt = '당신은 말을 할 수 있습니까?'
with torch.no_grad():
  tokens = tokenizer.encode(prompt, return_tensors='pt').to(device='cuda', non_blocking=True)
  gen_tokens = model.generate(tokens,     
    do_sample=True, #샘플링 전략 사용
    max_length=50, # 최대 디코딩 길이는 50
    top_k=50, # 확률 순위가 50위 밖인 토큰은 샘플링에서 제외
    top_p=0.95, # 누적 확률이 95%인 후보집합에서만 생성
    num_return_sequences=2, #2개의 결과를 디코딩해낸다
  )
  generated = tokenizer.batch_decode(gen_tokens)[0]
print(generated)  

## Beam Search 기반 

In [ ]:
prompt = '''당신은 AI입니다. 정말로 '언어'를 이해합니까?'''
with torch.no_grad():
  tokens = tokenizer.encode(prompt, return_tensors='pt').to(device='cuda', non_blocking=True)
  gen_tokens = model.generate(
      tokens, 
      max_length=100, 
      num_beams=5, #1보다 큰 값을 지정
      no_repeat_ngram_size=2, # 2-gram의 어구가 반복되지 않도록 설정함
      num_return_sequences=5, # 다섯 개의 문장을 리턴
      early_stopping=True #EOS토큰이 나오면 생성을 중단
  )
  generated = tokenizer.batch_decode(gen_tokens)[0]
print(generated)  


## Sampling 기반

In [ ]:
prompt = '''당신은 AI입니다. 정말로 '언어'를 이해합니까?'''
with torch.no_grad():
  tokens = tokenizer.encode(prompt, return_tensors='pt').to(device='cuda', non_blocking=True)
  gen_tokens = model.generate(
      tokens, 
      max_length=100, 
      do_sample=True, #샘플링 전략 사용
      top_k=50, # 확률 순위가 50위 밖인 토큰은 샘플링에서 제외
      top_p=0.95, # 누적 확률이 95%인 후보집합에서만 생성
      temperature= 0.75,# sharpness 조절 낮으면 shaprness 증가 randomness 감소 
      num_return_sequences=3 #3개의 결과를 디코딩해낸다
  )
  generated = tokenizer.batch_decode(gen_tokens)[0]
print(generated)  


- open-ended 생성에서는 top-k 확은 top-p 디코딩이 greedy 혹은 beam search보다 좋은 전략일 수 있다.

- 하지만 안타깝게도 top-k / top-p 샘플링 전략도 동어 반복 문제는 있다. (논문)

- 게다가, 모델의 훈련 목적 함수를 잘 조절하면 beam-search가 더 유창한 텍스트를 생성한다는 연구도 있다. (논문)

- 이는 open-ended 생성이 최근 빠르게 발전하는 연구분야인만큼, 어떤 하나의 전략이 "무조건 좋다"라고 말하기 어렵기 때문. 

- 포스팅에서 소개한 다양한 방법을 실험해보며 사용자의 태스크에 적합한 전략을 선택하는 것이 중요하다.

In [ ]:
prompt = '''
요즘은 흔히 연락하라는 말을 '카톡해'라고 하지만 10년전 카카오톡이 등장하기 전까지는 '문자해'라는 말이 일반적이었다. MSN 메신저, 네이트온 등 PC 메신저들이 유행해 '메신저'라는 개념에는 익숙했지만 스마트폰 도입이 갓 시작됐을 시기라 모바일 메신저 개념은 희미했다.
모바일을 통한 연락 수단이 전화와 문자 메시지였기 때문에 통신사 요금제 역시 통화 가능 시간과 문자의 갯수에 따라 달려졌다. 문자 한 건당 비용이 책정되는데다 70자가 넘으면 MMS로 전환돼 추가 요금이 부가돼 이용자들은 문자 전송에도 한땀한땀 정성을 다해야 했다.
때문에 당시 카카오톡의 등장은 센세이션 그 자체였다. 유료 문자메시지를 당연하게 사용했던 시절 글자 제한없는 문자를 무제한으로 보낼 수 있는데다 사진과 동영상까지 마음껏 전송할 수 있는 무료서비스 카카오톡은 문화 충격이나 다름 없었다.
문자뿐 아니라 통화 문화도 변했다. 2012년 당시 가입자가 3600만명에 달했던 카카오톡이 무료 음성통화 서비스 '보이스톡'을 선보이자 통신업계가 떠들썩해졌다. 카카오 보다 앞서 음성 통화 서비스를 선보인 마이피플, 라인 등은 크게 주목받지 못했지만 카카오톡은 높은 이용자수를 기반으로 보이스톡 서비스를 확장시켰다.
특히 보이스톡은 로밍 서비스에 가입하거나 국제 전화 서비스를 이용하지 않아도 데이터만 연결돼 있다면 해외에서도 카카오톡 친구와 무료 통화가 가능하다는 점 때문에 큰 화제를 모았다. 이때부터 해외 여행 시 로밍을 하지 않고 현지 유심을 구매하는 이들이 늘어나게 됐다.

한줄 요약:'''

with torch.no_grad():
  tokens = tokenizer.encode(prompt, return_tensors='pt').to(device='cuda', non_blocking=True)
  gen_tokens = model.generate(
      tokens, 
      max_length=50, 
      num_beams=5, #1보다 큰 값을 지정
      no_repeat_ngram_size=2, # 2-gram의 어구가 반복되지 않도록 설정함
      num_return_sequences=5, # 다섯 개의 문장을 리턴
      early_stopping=True #EOS토큰이 나오면 생성을 중단
  )
  generated = tokenizer.batch_decode(gen_tokens)[0]  
print(generated)

In [ ]:
prompt = '''

다음 문장을 서울 말투에서 북한 말투로 말투를 변환 합니다. 

서울 말투 : 배고파요, 우리 저기서 뭐라도 먹고갈까요?

북한 말투 : '''
with torch.no_grad():
  tokens = tokenizer.encode(prompt, return_tensors='pt').to(device='cuda', non_blocking=True)
  gen_tokens = model.generate(
      tokens,
      do_sample=True, #샘플링 전략 사용
      max_length=80, # 최대 디코딩 길이는 50
      top_k=50, # 확률 순위가 50위 밖인 토큰은 샘플링에서 제외
      top_p=0.95, # 누적 확률이 95%인 후보집합에서만 생성
      temperature= 0.75,
      num_return_sequences=3 #3개의 결과를 디코딩해낸다
  )
  generated = tokenizer.batch_decode(gen_tokens)
  
print(generated[0])

In [ ]:
prompt = '''
Translate the Korean sentence into English sentence 
Korean : "나 지금 많이 배고픈데, 우리 저기서 뭐라도 먹고갈까?"
English : "'''

with torch.no_grad():
  tokens = tokenizer.encode(prompt, return_tensors='pt').to(device='cuda', non_blocking=True)
  #두 전략을 섞어서 사용하면, 너무 낮게 랭킹된 토큰을 사용하는 것은 피하면서도 꽤나 다양한 시퀀스를 생성할 수 있다.

  sample_outputs = model.generate(
      tokens,
      do_sample=True, #샘플링 전략 사용
      max_length=70, # 최대 디코딩 길이는 50
      top_k=50, # 확률 순위가 50위 밖인 토큰은 샘플링에서 제외
      top_p=0.95, # 누적 확률이 95%인 후보집합에서만 생성
      temperature= 0.65,
      num_return_sequences=3 #3개의 결과를 디코딩해낸다
  )
    
  generated = tokenizer.batch_decode(sample_outputs)[0]
  
print(generated)

In [ ]:
prompt = '''
최고 핫한 인공지능, kogpt님과 인터뷰 나눠보겠습니다!
Q : kogpt님, 수월한 대화가 가능하신가요?
A : '''

with torch.no_grad():
  tokens = tokenizer.encode(prompt, return_tensors='pt').to(device='cuda', non_blocking=True)
  gen_tokens = model.generate(
      tokens, 
      max_length=100, 
      num_beams=5, #1보다 큰 값을 지정
      no_repeat_ngram_size=2, # 2-gram의 어구가 반복되지 않도록 설정함
      num_return_sequences=5, # 다섯 개의 문장을 리턴
      early_stopping=True #EOS토큰이 나오면 생성을 중단
  )
  generated = tokenizer.batch_decode(gen_tokens)[0]
  
print(generated)

In [ ]:
prompt = '''
최고 핫한 인공지능, kogpt님과 인터뷰 나눠보겠습니다!
Q : kogpt님, 수월한 대화가 가능하신가요?
A : '''

with torch.no_grad():
  tokens = tokenizer.encode(prompt, return_tensors='pt').to(device='cuda', non_blocking=True)
  gen_tokens = model.generate(
      tokens, 
      max_length=100, 
      do_sample=True, #샘플링 전략 사용
      top_k=50, # 확률 순위가 50위 밖인 토큰은 샘플링에서 제외
      top_p=0.95, # 누적 확률이 95%인 후보집합에서만 생성
      temperature= 0.75,# sharpness 조절 낮으면 shaprness 증가 randomness 감소 
      num_return_sequences=3 #3개의 결과를 디코딩해낸다
  )
  generated = tokenizer.batch_decode(gen_tokens)[0]
  
print(generated)

In [ ]:
prompt = '''
최고 핫한 인공지능, kogpt님과 인터뷰 나눠보겠습니다!
Q : kogpt님, 수월한 대화가 가능하신가요?
A : '''

with torch.no_grad():
  tokens = tokenizer.encode(prompt, return_tensors='pt').to(device='cuda', non_blocking=True)
  #gen_tokens = model.generate(tokens, do_sample=True, temperature=0.85, max_length=128)
  gen_tokens = model.generate(
      tokens,
      do_sample=True, #샘플링 전략 사용
      max_length=256, # 최대 디코딩 길이는 50
      top_k=50, # 확률 순위가 50위 밖인 토큰은 샘플링에서 제외
      top_p=0.95, # 누적 확률이 95%인 후보집합에서만 생성
      temperature= 0.85,
      num_return_sequences=3 #3개의 결과를 디코딩해낸다
  )
    
  generated = tokenizer.batch_decode(gen_tokens)[0]
  
print(generated)